config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  root 'top#index'
  get 'relationships/create'
  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :conversations do
    resources :messages
  end

  resources :blogs, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end

  resources :contacts, only:[:index, :new, :create, :destroy]do
    collection do
      post :confirm
    end
  end

  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :poems, only: [:index, :show]

  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end
end

app/models/poem.rb
class Poem < ActiveResource::Base
  self.site = "https://boiling-basin-96834.herokuapp.com/"
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  def index
    @poems = Poem.all
  end

  def show
    @poems = Poem.find(params[:id])
  end

end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/poems/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <% @poems.each do |poem| %>
    <div class="row">
      <h4><strong>タイトル：<%= poem.title %></strong></h4>
      <%= link_to "詳細", poem_path(poem.id), class: 'btn btn-default btn-sm btn-success' %>
    </div>
    <% end %>
  </div>
</div>

app/views/poems/show.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
      内容：<p><%= @poems.content %></p>
      <%= link_to "一覧に戻る", poems_path %>
  </div>
</div>